### ISSUE TITLE
wp-admin does not access

### ISSUE THREAD

**Issue by redbox-cdn** [tarosky/http2-server-push#3]
About v0.6.0 does not work on my site 

Nginx 1.13.9 or later
WordPress 4.9 or later
PHP 7 or later

when I  enabled this plugin, wp-admin does not access. status code 502.

if you have any information necessary to solve,please let me know

**Comment by miya0001** [comment]
I guess there are too much JS and CSS to load.
If you are using Nginx, you should increase the size of buffers.
https://github.com/tarosky/http2-server-push-preload#configurating-http2-server-push-for-nginx

**Comment by miya0001** [comment]
Anyway, could we have discussion to improve speed for WordPress.
Actually, I realized that this solution doesn't improve site speed, because the browsers won't use client side cache of resources which are pushed via HTTP/2.

**Comment by redbox-cdn** [comment]
@miya0001 Thank you for reply. This problem related to our server. 
 adjusted proxy_buffers size,the wp-admin  works normally again.
